# " Pandas is used for data manipulation on rows and columns only "

## To create a data

In [12]:
import pandas as pd
list = [[1,2,3,],[4,5,6]]
df = pd.DataFrame(list)     # ----> () can be any thing {list,ditionary,sets,etc} [rows and column only]

## To print the data

In [13]:
print(df)

   0  1  2
0  1  2  3
1  4  5  6

In [14]:
print(df.head())    # ----> top 5 elements
print(df.tail())    # ----> bottum 5 elements

   0  1  2
0  1  2  3
1  4  5  6
   0  1  2
0  1  2  3
1  4  5  6

## Some useful operations

1. df.info()                 --> To know more about data
2. df.nunique()              --> To know more about uniqueness in data
3. df.describe()             --> To know about mean , std , var , etc
4. df["a"].unique()          --> To know more about col , uniquelly
5. df.shape                  --> To know more about shape

## Loading dataframes from files

In [ ]:
import pandas as pd
sample = pd.read_csv("D:\\Machine Learning\\Pandas\\customers-100.csv")
print(sample)

In [ ]:
sample.to_excel   # to change file type

## Accessing data

In [2]:
import pandas as pd
sample = pd.read_csv("D:\\Machine Learning\\Pandas\\samplefile.csv")

In [ ]:
print(sample.head(4))

In [ ]:
print(sample.tail(4))

In [ ]:
print(sample.sample())          # for random sample

In [51]:
print(sample.loc[0,"Age"])       # syntax : sample.loc[row_no. , "Col_name"] { for specific data access }

28

In [ ]:
print(sample.iloc[:3 , 1:])       # syntax : sample.iloc[ row slice , col slice] { for specific row and col data}

" In 'loc' , the data is access through col name. In 'iloc' they are accessed through col number "

In [ ]:
sample_new = sample.iloc[2:6 , 2:4 ]       # for creating a duplicate sample. SO that it can be used to rewrite data
print(sample_new)

In [ ]:
print(sample.at[0,"Age"])         # same as loc

28

In [ ]:
sample.sort_values

In [ ]:
sample.sort_values(["Name","Age"] , ascending=[1,0])      # 1 true for Col_name , 0 false for Col_age

## Filtering Data

In [5]:
sample[sample["Age"] > 30]

    ID              Name  Age   Department  Salary
2    3     Michael Brown   32      Finance   62000
4    5    William Wilson   35  Engineering   70000
6    7    James Anderson   31  Engineering   65000
10  11     Lucas Jackson   33  Engineering   69000
12  13         Mason Lee   36      Finance   73000
14  15       Ethan White   34  Engineering   71000
20  21        Liam Allen   35  Engineering   72000
22  23  Daniel Hernandez   31    Marketing   57000
24  25     Samuel Wright   33       Design   52000
26  27       David Green   32  Engineering   67500
28  29      Joseph Baker   34    Marketing   58000

In [6]:
sample.loc[sample["Salary"] > 65000 , ["Name"]]

              Name
4   William Wilson
10   Lucas Jackson
12       Mason Lee
14     Ethan White
20      Liam Allen
26     David Green

In [14]:
sample[(sample['Age'] > 32) & (sample['Salary'] > 63000)]

    ID            Name  Age   Department  Salary
4    5  William Wilson   35  Engineering   70000
10  11   Lucas Jackson   33  Engineering   69000
12  13       Mason Lee   36      Finance   73000
14  15     Ethan White   34  Engineering   71000
20  21      Liam Allen   35  Engineering   72000

In [17]:
sample[sample['Name'].str.contains("John")]

   ID          Name  Age   Department  Salary
0   1    John Smith   28  Engineering   58000
1   2  Emma Johnson   25    Marketing   51000

In [24]:
sample[sample['Name'].str.contains("John | smith")]

   ID        Name  Age   Department  Salary
0   1  John Smith   28  Engineering   58000

In [26]:
sample[sample['Age'].isin([34,45,35])]

    ID            Name  Age   Department  Salary
4    5  William Wilson   35  Engineering   70000
14  15     Ethan White   34  Engineering   71000
20  21      Liam Allen   35  Engineering   72000
28  29    Joseph Baker   34    Marketing   58000

In [32]:
sample.query('Salary == 70000')

   ID            Name  Age   Department  Salary
4   5  William Wilson   35  Engineering   70000

## Add / Remove columns

In [ ]:
sample1 = sample.copy()
sample1['Address'] = "Usa"          # ---> Add same element to all values
print(sample1)

In [ ]:
import numpy as np
sample1['Company'] = np.where(sample1['Age'] > 30 , 'Microsoft' , 'Apple')      # ----> To add new col and data according to the condition
print(sample1)

In [ ]:
sample1 = sample.drop(columns=['Company','Age','ID'])
print(sample1)

In [ ]:
sample1 = sample1[['Name','Salary','Address']]
print(sample1)

In [ ]:
sample1 = sample.copy()
sample1['New_salary'] = sample1['ID'] /  sample1['Salary']
print(sample1)

In [ ]:
sample1['New_col'] = sample1['Name'].str.split(' ').str[0]
print(sample1.head())

In [78]:
sample1.to_csv("path",index=False)

In [ ]:
sample1['new_col3'] = sample1['Salary'].apply(lambda X: 'Yes' if X  > 65000 else 'No')
sample1

In [ ]:
sample1['New'] = sample1['Name'].str.split(" ").str[0]
sample1.drop(columns='New')

In [ ]:
def fun(row):
    if row['Age'] > 30 and row['Salary'] > 65000:
        return 'Eligible'
    else:
        return 'Not Eligible'

sample1['New_col'] = sample1.apply(fun, axis=1)   # axis = 1 (rows) and axis = 0 (column)
sample1

## Merging and Concatenating data

In [129]:
sample_1 = pd.read_csv("D:\\Machine Learning\\Pandas\\sample_file.csv")
file = pd.read_csv("D:\\Machine Learning\\Pandas\\samplefile.csv")

file_new = pd.merge(sample_1,file, left_on='OrderID', right_on='ID' , how="left")
file

    ID              Name  Age       Department  Salary
0    1        John Smith   28      Engineering   58000
1    2      Emma Johnson   25        Marketing   51000
2    3     Michael Brown   32          Finance   62000
3    4      Olivia Davis   29  Human Resources   54000
4    5    William Wilson   35      Engineering   70000
5    6      Ava Martinez   27           Design   49000
6    7    James Anderson   31      Engineering   65000
7    8     Sophia Thomas   24            Sales   47000
8    9   Benjamin Taylor   30          Finance   60000
9   10    Isabella Moore   26        Marketing   52000
10  11     Lucas Jackson   33      Engineering   69000
11  12        Mia Martin   23            Sales   45000
12  13         Mason Lee   36          Finance   73000
13  14   Charlotte Perez   28           Design   50000
14  15       Ethan White   34      Engineering   71000
15  16     Amelia Harris   25  Human Resources   53000
16  17   Alexander Clark   29        Marketing   56000
17  18      Harper Lewis   27          Finance   61000
18  19      Henry Walker   30      Engineering   64000
19  20       Evelyn Hall   26            Sales   48000
20  21        Liam Allen   35      Engineering   72000
21  22     Abigail Young   28  Human Resources   55000
22  23  Daniel Hernandez   31        Marketing   57000
23  24    Elizabeth King   24          Finance   46000
24  25     Samuel Wright   33           Design   52000
25  26       Grace Scott   27            Sales   49500
26  27       David Green   32      Engineering   67500
27  28       Chloe Adams   29          Finance   62500
28  29      Joseph Baker   34        Marketing   58000
29  30     Nora Gonzalez   25  Human Resources   52500

In [130]:
file

    ID              Name  Age       Department  Salary
0    1        John Smith   28      Engineering   58000
1    2      Emma Johnson   25        Marketing   51000
2    3     Michael Brown   32          Finance   62000
3    4      Olivia Davis   29  Human Resources   54000
4    5    William Wilson   35      Engineering   70000
5    6      Ava Martinez   27           Design   49000
6    7    James Anderson   31      Engineering   65000
7    8     Sophia Thomas   24            Sales   47000
8    9   Benjamin Taylor   30          Finance   60000
9   10    Isabella Moore   26        Marketing   52000
10  11     Lucas Jackson   33      Engineering   69000
11  12        Mia Martin   23            Sales   45000
12  13         Mason Lee   36          Finance   73000
13  14   Charlotte Perez   28           Design   50000
14  15       Ethan White   34      Engineering   71000
15  16     Amelia Harris   25  Human Resources   53000
16  17   Alexander Clark   29        Marketing   56000
17  18      Harper Lewis   27          Finance   61000
18  19      Henry Walker   30      Engineering   64000
19  20       Evelyn Hall   26            Sales   48000
20  21        Liam Allen   35      Engineering   72000
21  22     Abigail Young   28  Human Resources   55000
22  23  Daniel Hernandez   31        Marketing   57000
23  24    Elizabeth King   24          Finance   46000
24  25     Samuel Wright   33           Design   52000
25  26       Grace Scott   27            Sales   49500
26  27       David Green   32      Engineering   67500
27  28       Chloe Adams   29          Finance   62500
28  29      Joseph Baker   34        Marketing   58000
29  30     Nora Gonzalez   25  Human Resources   52500

In [135]:
file_engg = file[file['Department'] == 'Engineering'].copy()
file_fin = file[file['Department'] == 'Finance'].copy()
file_fin

    ID             Name  Age Department  Salary
2    3    Michael Brown   32    Finance   62000
8    9  Benjamin Taylor   30    Finance   60000
12  13        Mason Lee   36    Finance   73000
17  18     Harper Lewis   27    Finance   61000
23  24   Elizabeth King   24    Finance   46000
27  28      Chloe Adams   29    Finance   62500

In [137]:
new_df = pd.concat([file_engg,file_fin])
new_df

    ID             Name  Age   Department  Salary
0    1       John Smith   28  Engineering   58000
4    5   William Wilson   35  Engineering   70000
6    7   James Anderson   31  Engineering   65000
10  11    Lucas Jackson   33  Engineering   69000
14  15      Ethan White   34  Engineering   71000
18  19     Henry Walker   30  Engineering   64000
20  21       Liam Allen   35  Engineering   72000
26  27      David Green   32  Engineering   67500
2    3    Michael Brown   32      Finance   62000
8    9  Benjamin Taylor   30      Finance   60000
12  13        Mason Lee   36      Finance   73000
17  18     Harper Lewis   27      Finance   61000
23  24   Elizabeth King   24      Finance   46000
27  28      Chloe Adams   29      Finance   62500

## Handling Null values

In [ ]:
import pandas as pd
import numpy as np
sample = pd.read_csv("D:\\Machine Learning\\Pandas\\sample.csv")
sample_2 = sample.copy() 
sample_2.loc[1:2,"Salary"] = np.nan                            # ---> To insert NaN values to that interval
sample_2

In [ ]:
sample_2.fillna(20)        # ---> To fill na values with that values

In [ ]:
sample = pd.read_csv("D:\\Machine Learning\\Pandas\\sample.csv")
sample_2 = sample.copy() 
sample_2.fillna(sample_2['Salary'].mean())

In [ ]:
sample = pd.read_csv("D:\\Machine Learning\\Pandas\\sample.csv")
sample_2 = sample.copy() 
sample_2['Age'].interpolate()        # ---> Fill na from neighbour values

In [ ]:
sample_2.dropna(subset=['Age'],inplace=True)   # ---> inplace means it will modify the original file
sample_2

In [ ]:
sample_2[sample_2['Salary'].isna()]

In [ ]:
sample_2[sample_2['Salary'].notna()]

## Aggregating Data

In [24]:
sample = pd.read_csv("D:\\Machine Learning\\Pandas\\sample_file.csv")
sample = sample.copy() 
sample

    OrderID                    Item     Category  Quantity  BillAmount
0         1        Margherita Pizza        Pizza         1         249
1         2            Paneer Tikka      Starter         2         340
2         3         Chicken Biryani  Main Course         1         299
3         4             Cold Coffee     Beverage         1         120
4         5            French Fries      Starter         1          99
5         6             Masala Dosa  Main Course         1         150
6         7           Cheese Burger       Burger         2         260
7         8         Choco Lava Cake      Dessert         1         130
8         9          Butter Chicken  Main Course         1         350
9        10            Garlic Bread      Starter         1         149
10       11                   Pepsi     Beverage         2          70
11       12          Veg Fried Rice  Main Course         1         180
12       13           Chicken Momos      Starter         1         160
13       14        Ice Cream Sundae      Dessert         1         140
14       15            Chicken Wrap       Snacks         1         170
15       16          Mango Smoothie     Beverage         1         150
16       17           Pasta Alfredo  Main Course         1         260
17       18           Chicken Pizza        Pizza         1         320
18       19            Caesar Salad        Salad         1         200
19       20           Hot Chocolate     Beverage         1         140
20       21          Paneer Biryani  Main Course         1         270
21       22         Peri Peri Fries      Starter         1         120
22       23       BBQ Chicken Wings      Starter         1         250
23       24  Brownie with Ice Cream      Dessert         1         180
24       25           Club Sandwich       Snacks         1         190
25       26           Veggie Burger       Burger         1         130
26       27                Lemonade     Beverage         1          80
27       28    Paneer Butter Masala  Main Course         1         310
28       29           Tandoori Roti  Main Course         3          45
29       30         Cheese Sandwich       Snacks         1         160

In [29]:
sample[sample['Category']=='Starter']['Item'].value_counts()

Item
Paneer Tikka         1
French Fries         1
Garlic Bread         1
Chicken Momos        1
Peri Peri Fries      1
BBQ Chicken Wings    1
Name: count, dtype: int64

In [42]:
sample.groupby(['Category'])['BillAmount'].sum()

Category
Beverage        560
Burger          390
Dessert         450
Main Course    1864
Pizza           569
Salad           200
Snacks          520
Starter        1118
Name: BillAmount, dtype: int64

In [ ]:
sample.groupby(['Category']).agg({'Quantity': 'sum', 'BillAmount': 'mean'})

             Quantity  BillAmount
Category
Beverage            6  112.000000
Burger              3  195.000000
Dessert             3  150.000000
Main Course        10  233.000000
Pizza               2  284.500000
Salad               1  200.000000
Snacks              3  173.333333
Starter             7  186.333333

## Advanced Funtionality

In [ ]:
sample['New_col'] = sample['Quantity'].shift(1)  # --- Shift exist col down in new col

In [56]:
sample['New_col1'] = sample['Quantity'].rank(ascending=True)         # --- rank acording to the given col

In [ ]:
sample['New_col2'] = sample['Quantity'].cumsum()     # --- add things as we go down